### ISSUE TITLE
IndexOutOfBoundsException in BruteForcePackager.fit2d

### ISSUE THREAD

**Issue by jotoh98** [skjolber/3d-bin-container-packing#245]
Using the java 8 version, my code 

	final List<BoxItem> parcels = Arrays.asList(
		new BoxItem(new Box(430, 390, 40, 0), 2),
		new BoxItem(new Box(430, 390, 730, 0))
	);
	
	final List<Container> containers = Arrays.asList(
		new Container(440, 400, 90, 0),
		new Container(440, 400, 190, 0),
		new Container(440, 400, 380, 0),
		new Container(440, 400, 740, 0)
	);
 
	Packager packager = BruteForcePackager.newBuilder()
		.withContainers(containers)
		.build();
 
	final List<Container> usedContainers = packager.packList(parcels, 3, () -> false);

produces the following `IndexOutOfBoundsException`

	Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList$SubList.rangeCheck(ArrayList.java:1225)
	at java.util.ArrayList$SubList.get(ArrayList.java:1042)
	at com.github.skjolber.packing.BruteForcePackager.fit2D(BruteForcePackager.java:194)
	at com.github.skjolber.packing.BruteForcePackager.pack(BruteForcePackager.java:148)
	at com.github.skjolber.packing.BruteForcePackager.pack(BruteForcePackager.java:72)
	at com.github.skjolber.packing.BruteForcePackager$BruteForceAdapter.attempt(BruteForcePackager.java:536)
	at com.github.skjolber.packing.Packager.packList(Packager.java:279)
	at Main.main(Main.java:26)

In `fit2d`, the methods `placements` list parameter has lesser fields than the passed `index` demands. I don't know what the expected behaviour is in that case or if this error is only reproducable in the Java 8 version.

Im not expecting the missing weights (which are not important in my use case) to be a problem. The implementation of the LAFF packager produces an output.

**Comment by skjolber** [comment]
@jotoh98 thanks for the bug report, if you want, please verify https://github.com/skjolber/3d-bin-container-packing/pull/247 (or I'll release it in a few days anyways as the unit test passes).
