### ISSUE TITLE
ArrayIndexOutOfBoundsException on the visualizer

### ISSUE THREAD

**Issue by khorchanov** [skjolber/3d-bin-container-packing#665]
With `LargestAreaFitFirstPackager` algo, I usually have this problem with the visualizer : 

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at com.github.skjolber.packing.ep.points3d.Point3DFlagList.get(Point3DFlagList.java:63)
	at com.github.skjolber.packing.ep.points3d.ExtremePoints3D.add(ExtremePoints3D.java:116)
	at com.github.skjolber.packing.visualizer.packaging.DefaultPackagingResultVisualizerFactory.visualize(DefaultPackagingResultVisualizerFactory.java:74)
	at com.github.skjolber.packing.visualizer.packaging.AbstractPackagingResultVisualizerFactory.visualize(AbstractPackagingResultVisualizerFactory.java:15)
	at com.github.skjolber.packing.visualizer.packaging.AbstractPackagingResultVisualizerFactory.visualize(AbstractPackagingResultVisualizerFactory.java:28)
	at Issue.write(Issue.java:45)
	at Issue.main(Issue.java:34)
```
Example :
**Please note that if I activate 3d rotation with boxes the problem disappears**
```java

import com.github.skjolber.packing.api.*;
import com.github.skjolber.packing.packer.laff.LargestAreaFitFirstPackager;
import com.github.skjolber.packing.visualizer.packaging.DefaultPackagingResultVisualizerFactory;

import java.io.File;
import java.util.Arrays;
import java.util.List;

public class Issue {

    private static List<StackableItem> products = Arrays.asList(
            new StackableItem(Box.newBuilder().withDescription("1").withSize(395, 260, 185).withWeight(7).build(), 41),
            new StackableItem(Box.newBuilder().withDescription("2").withSize(335, 175, 160).withWeight(6).build(), 2),
            new StackableItem(Box.newBuilder().withDescription("3").withSize(530, 255, 150).withWeight(5).build(), 1));

    private static Container container = Container.newBuilder().withDescription("1")
            .withEmptyWeight(0)
            .withSize(1200, 800, 2000)
            .withMaxLoadWeight(1000)
            .build();


    public static void main(String[] args) throws Exception {
        LargestAreaFitFirstPackager laff_packager = LargestAreaFitFirstPackager.newBuilder()
                .build();

        List<ContainerItem> containerItems = ContainerItem
                .newListBuilder()
                .withContainer(container)
                .build();

        PackagerResult result = laff_packager.newResultBuilder().withContainers(containerItems).withStackables(products).build();
        if (result.isSuccess()) {
            write(result.get(0));
        } else {
            System.out.println("Impossible to stack");
        }
        System.out.println("Finished");
    }

    private static void write(Container container) throws Exception {
        DefaultPackagingResultVisualizerFactory p = new DefaultPackagingResultVisualizerFactory();

        File file = new File("./src/viewer/public/assets/containers.json");
        p.visualize(Arrays.asList(container), file);
    }
}


```

**Comment by skjolber** [comment]
I think the problem is that the vizualiser can't reproduce the points due to the LAFF packager adjusting the free space between each level (and the visualizer does not).

**Comment by khorchanov** [comment]
Any news on this ? Cuz for now the LAFF is unusable due to this problem :(

**Comment by skjolber** [comment]
@khorchanov well the fastest approach would be to skip displaying the points, i.e. just the stacked boxes. But why is it unusable, this is just the visualizer?

**Comment by khorchanov** [comment]
yes, so if you have any hacks to display and see the stacking result that would be great

**Comment by skjolber** [comment]
@khorchanov try the latest master
