### ISSUE TITLE
Not able to fit boxitems

### ISSUE THREAD

**Issue by balachandarsv** [skjolber/3d-bin-container-packing#83]
Container : width - 22 depth - 22 height - 22 weight - 35 name - 5
BoxItems :  width - 10 depth - 10 height - 10 weight - 10 name - A - Count  5
Max Containers = 10

For the above input, 
```
Exception in thread "main" java.lang.IllegalArgumentException: Remaining weight is negative at -5
	at com.github.skjolberg.packing.Container.getFreeWeight(Container.java:125)
	at com.github.skjolberg.packing.LargestAreaFitFirstPackager.fit2D(LargestAreaFitFirstPackager.java:201)
	at com.github.skjolberg.packing.LargestAreaFitFirstPackager.pack(LargestAreaFitFirstPackager.java:148)
	at com.github.skjolberg.packing.LargestAreaFitFirstPackager$1.attempt(LargestAreaFitFirstPackager.java:457)
	at com.github.skjolberg.packing.Packager.packList(Packager.java:282)
	at Main.main(Main.java:38)
```

When the weight becomes negative, I guess the algorithm is not moving to the next container.
Can you please look into this?

**Comment by skjolber** [comment]
@balachandarsv can you create a PR with a (failing) unit test?

**Comment by skjolber** [comment]
@balachandarsv thanks for the bug report & unit tests! I've released a new version with the fix.
